# Generated by Django 5.2.4 on 2025-07-11 12:59

import localflavor.in_.models
import users.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_location_state_location_zip_code_profile_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='state',
            field=localflavor.in_.models.INStateField(max_length=2),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(null=True, upload_to=users.utils.user_directory_path),
        ),
    ]
