CARS_BRANDS = (
    ('maruti', 'Maruti'),
    ('hyundai', 'Hyundai'),
    ('honda', 'Honda'),
    ('tata', 'Tata'),
    ('renault', 'Renault'),
    ('kia', 'KIA'),
    ('mahindra', 'Mahindra'),
    ('ford', 'Ford'),
    ('volkswagen', 'Volkswagen'),
    ('nissan', 'Nissan'),
    ('mg', 'MG'),
    ('toyota', 'Toyota'),
    ('datsun', 'Datsun'),
    ('skoda', 'Skoda'),
    ('jeep', 'Jeep')
)

MODELS = (
    ('triber rxz amt', 'Triber Rxz Amt'),
    ('seltos htx 1.5 diesel', 'Seltos Htx 1.5 Diesel'),
    ('amaze 1.2l i-vtec s at', 'Amaze 1.2L I-Vtec S At'),
    ('vitara brezza zxi plus at shvs', 'Vitara Brezza Zxi Plus At Shvs'),
    ('urban cruiser premium grade mt', 'Urban Cruiser Premium Grade Mt'),
    ('ecosport ambiente 1.5l diesel', 'Ecosport Ambiente 1.5L Diesel'),
    ('seltos htx 1.5 cvt petrol', 'Seltos Htx 1.5 Cvt Petrol'),
    ('swift dzire vxi (o)', 'Swift Dzire Vxi (O)'),
    ('nexon xm sunroof petrol', 'Nexon Xm Sunroof Petrol'),
    ('swift dzire zdi', 'Swift Dzire Zdi'),
    ('grand i10 sportz 1.2 kappa vtvt', 'Grand I10 Sportz 1.2 Kappa Vtvt'),
    ('taigun gt plus 1.5 tsi dsg', 'Taigun Gt Plus 1.5 Tsi Dsg'),
    ('redi go a', 'Redi Go A'),
    ('wagon r 1.0 vxi+ amt', 'Wagon R 1.0 Vxi+ Amt'),
    ('xuv500 w10', 'Xuv500 W10'),
    ('amaze 1.2l i-vtec vx', 'Amaze 1.2L I-Vtec Vx'),
    ('creta sx plus at 1.6 petrol', 'Creta Sx Plus At 1.6 Petrol'),
    ('brio s mt', 'Brio S Mt'),
    ('amaze 1.2l i-vtec s', 'Amaze 1.2L I-Vtec S'),
    ('redi go t(o) 1.0', 'Redi Go T(O) 1.0'),
    ('hector sharp hybrid 1.5 petrol', 'Hector Sharp Hybrid 1.5 Petrol'),
    ('altroz xza plus', 'Altroz Xza Plus'),
    ('i20 sportz 1.4 crdi', 'I20 Sportz 1.4 Crdi'),
    ('nexon xz plus petrol sunroof', 'Nexon Xz Plus Petrol Sunroof'),
    ('grand i10 nios era 1.2 kappa vtvt', 'Grand I10 Nios Era 1.2 Kappa Vtvt'),
    ('micra active xv', 'Micra Active Xv'),
    ('nexon xz plus petrol dual tone', 'Nexon Xz Plus Petrol Dual Tone'),
    ('new i20  asta 1.0 turbo imt dual tone', 'New I20  Asta 1.0 Turbo Imt Dual Tone'),
    ('city 1.5l i-vtec vx', 'City 1.5L I-Vtec Vx'),
    ('kwid rxt 1.0 amt (o)', 'Kwid Rxt 1.0 Amt (O)'),
    ('baleno alpha cvt petrol 1.2', 'Baleno Alpha Cvt Petrol 1.2'),
    ('ciaz alpha  at 1.5 shvs petrol', 'Ciaz Alpha  At 1.5 Shvs Petrol'),
    ('tiago xz plus dual tone petrol', 'Tiago Xz Plus Dual Tone Petrol'),
    ('ecosport trend 1.5l diesel', 'Ecosport Trend 1.5L Diesel'),
    ('ertiga vxi', 'Ertiga Vxi'),
    ('baleno delta petrol 1.2', 'Baleno Delta Petrol 1.2'),
    ('seltos htk plus 1.5 imt', 'Seltos Htk Plus 1.5 Imt'),
    ('xuv700 ax 7 luxury p at 7 str', 'Xuv700 Ax 7 Luxury P At 7 Str'),
    ('celerio vxi (o)', 'Celerio Vxi (O)'),
    ('city 1.5l i-vtec v mt', 'City 1.5L I-Vtec V Mt'),
    ('taigun highline 1.0 tsi at', 'Taigun Highline 1.0 Tsi At'),
    ('eeco 5 str ac (o)', 'Eeco 5 Str Ac (O)'),
    ('swift vxi', 'Swift Vxi'),
    ('tigor xz plus petrol', 'Tigor Xz Plus Petrol'),
    ('xuv300 w8 (o) 1.5 diesel', 'Xuv300 W8 (O) 1.5 Diesel'),
    ('nexon xz plus (hs) diesel', 'Nexon Xz Plus (Hs) Diesel'),
    ('wagon r 1.0 vxi+', 'Wagon R 1.0 Vxi+'),
    ('vitara brezza zdi', 'Vitara Brezza Zdi'),
    ('vitara brezza zdi plus', 'Vitara Brezza Zdi Plus'),
    ('ignis alpha 1.2', 'Ignis Alpha 1.2'),
    ('hector sharp 1.5 petrol cvt', 'Hector Sharp 1.5 Petrol Cvt'),
    ('s presso vxi+', 'S Presso Vxi+'),
    ('a star vxi', 'A Star Vxi'),
    ('baleno zeta cvt petrol 1.2', 'Baleno Zeta Cvt Petrol 1.2'),
    ('jazz 1.2l i-vtec v at', 'Jazz 1.2L I-Vtec V At'),
    ('ignis delta 1.2 amt', 'Ignis Delta 1.2 Amt'),
    ('thar lx  p 4wd at convertible', 'Thar Lx  P 4Wd At Convertible'),
    ('grand i10 nios asta u2 1.2 crdi', 'Grand I10 Nios Asta U2 1.2 Crdi'),
    ('kwid climber 1.0 (o)', 'Kwid Climber 1.0 (O)'),
    ('nexon xza plus petrol', 'Nexon Xza Plus Petrol'),
    ('kwid rxt 1.0 (o)', 'Kwid Rxt 1.0 (O)'),
    ('city 1.5l i-vtec vx cvt', 'City 1.5L I-Vtec Vx Cvt'),
    ('creta e plus 1.6 petrol', 'Creta E Plus 1.6 Petrol'),
    ('duster rxz 1.3 turbo petrol mt', 'Duster Rxz 1.3 Turbo Petrol Mt'),
    ('swift zxi', 'Swift Zxi'),
    ('creta sx at 1.6 petrol', 'Creta Sx At 1.6 Petrol'),
    ('kwid climber 1.0 amt', 'Kwid Climber 1.0 Amt'),
    ('nexon xz plus (hs) petrol', 'Nexon Xz Plus (Hs) Petrol'),
    ('wr-v 1.2l i-vtec sv mt', 'Wr-V 1.2L I-Vtec Sv Mt'),
    ('venue sx 1.0 (o) turbo', 'Venue Sx 1.0 (O) Turbo'),
    ('new wagon-r lxi cng (o) 1.0', 'New Wagon-R Lxi Cng (O) 1.0'),
    ('swift lxi', 'Swift Lxi'),
    ('tigor xz petrol', 'Tigor Xz Petrol'),
    ('nexon xza plus (o) petrol dual tone', 'Nexon Xza Plus (O) Petrol Dual Tone'),
    ('i10 magna 1.2', 'I10 Magna 1.2'),
    ('celerio vxi amt', 'Celerio Vxi Amt'),
    ('creta s 1.4 diesel', 'Creta S 1.4 Diesel'),
    ('baleno alpha petrol 1.2', 'Baleno Alpha Petrol 1.2'),
    ('ertiga lxi', 'Ertiga Lxi'),
    ('jazz 1.2l i-vtec v cvt', 'Jazz 1.2L I-Vtec V Cvt'),
    ('ciaz alpha 1.4 petrol', 'Ciaz Alpha 1.4 Petrol'),
    ('freestyle trend 1.2 petrol', 'Freestyle Trend 1.2 Petrol'),
    ('grand i10 asta at 1.2 kappa vtvt', 'Grand I10 Asta At 1.2 Kappa Vtvt'),
    ('nexon xza plus petrol dual tone', 'Nexon Xza Plus Petrol Dual Tone'),
    ('city 1.5l i-vtec v at', 'City 1.5L I-Vtec V At'),
    ('kwid rxt 0.8', 'Kwid Rxt 0.8'),
    ('celerio vxi cng', 'Celerio Vxi Cng'),
    ('verna fluidic 1.6 vtvt sx opt', 'Verna Fluidic 1.6 Vtvt Sx Opt'),
    ('new santro sportz cng', 'New Santro Sportz Cng'),
    ('ameo highline plus 1.5l at 16 alloy', 'Ameo Highline Plus 1.5L At 16 Alloy'),
    ('nexon xza plus diesel dark edition', 'Nexon Xza Plus Diesel Dark Edition'),
    ('alto k10 vxi', 'Alto K10 Vxi'),
    ('nexon xza plus (o) petrol', 'Nexon Xza Plus (O) Petrol'),
    ('hector sharp 1.5 dct petrol', 'Hector Sharp 1.5 Dct Petrol'),
    ('xcent s (o) 1.2', 'Xcent S (O) 1.2'),
    ('altroz xz i-turbo petrol', 'Altroz Xz I-Turbo Petrol'),
    ('nexon xza plus diesel dual tone', 'Nexon Xza Plus Diesel Dual Tone'),
    ('go t', 'Go T'),
    ('i20 sportz 1.2', 'I20 Sportz 1.2'),
    ('magnite xe', 'Magnite Xe'),
    ('venue sx 1.0 turbo', 'Venue Sx 1.0 Turbo'),
    ('xuv300 w8 1.5 diesel amt', 'Xuv300 W8 1.5 Diesel Amt'),
    ('sonet htk plus 1.0 dct', 'Sonet Htk Plus 1.0 Dct'),
    ('swift vxi amt', 'Swift Vxi Amt'),
    ('elite i20 sportz 1.2', 'Elite I20 Sportz 1.2'),
    ('s presso lxi', 'S Presso Lxi'),
    ('alto vxi', 'Alto Vxi'),
    ('city 1.5l i-vtec zx cvt', 'City 1.5L I-Vtec Zx Cvt'),
    ('new wagon-r lxi 1.0', 'New Wagon-R Lxi 1.0'),
    ('ecosport titanium 1.5l petrol at', 'Ecosport Titanium 1.5L Petrol At'),
    ('punch creative  1.2 rtn dual tone', 'Punch Creative  1.2 Rtn Dual Tone'),
    ('ameo comfortline 1.0l', 'Ameo Comfortline 1.0L'),
    ('compass limited (o) 2.0 diesel 4x4', 'Compass Limited (O) 2.0 Diesel 4X4'),
    ('virtus comfortline tsi 1.0 mt', 'Virtus Comfortline Tsi 1.0 Mt'),
    ('celerio x zxi (o) amt', 'Celerio X Zxi (O) Amt'),
    ('grand i10 asta (o) 1.2 kappa vtvt', 'Grand I10 Asta (O) 1.2 Kappa Vtvt'),
    ('grand i10 magna 1.1 crdi', 'Grand I10 Magna 1.1 Crdi'),
    ('xcent s 1.2', 'Xcent S 1.2'),
    ('kwid rxt 1.0', 'Kwid Rxt 1.0'),
    ('ciaz zeta at 1.5  shvs petrol', 'Ciaz Zeta At 1.5  Shvs Petrol'),
    ('celerio zxi (o)', 'Celerio Zxi (O)'),
    ('jazz 1.2l i-vtec zx', 'Jazz 1.2L I-Vtec Zx'),
    ('wagon r 1.0 vxi', 'Wagon R 1.0 Vxi'),
    ('ciaz alpha 1.5 shvs petrol', 'Ciaz Alpha 1.5 Shvs Petrol'),
    ('ciaz s 1.5 mt petrol', 'Ciaz S 1.5 Mt Petrol'),
    ('nexon xza plus (l)', 'Nexon Xza Plus (L)'),
    ('creta sx (o) 1.6 petrol', 'Creta Sx (O) 1.6 Petrol'),
    ('grand i10 asta 1.2 kappa vtvt', 'Grand I10 Asta 1.2 Kappa Vtvt'),
    ('alto 800 lxi', 'Alto 800 Lxi'),
    ('new wagon-r vxi 1.2', 'New Wagon-R Vxi 1.2'),
    ('swift zxi amt', 'Swift Zxi Amt'),
    ('elite i20 asta 1.2', 'Elite I20 Asta 1.2'),
    ('venue s 1.2', 'Venue S 1.2'),
    ('i20 active 1.2 s', 'I20 Active 1.2 S'),
    ('ignis alpha 1.2 amt', 'Ignis Alpha 1.2 Amt'),
    ('nexon xza plus (hs) petrol', 'Nexon Xza Plus (Hs) Petrol'),
    ('amaze 1.2l i-vtec ex', 'Amaze 1.2L I-Vtec Ex'),
    ('creta sx plus 1.6 petrol', 'Creta Sx Plus 1.6 Petrol'),
    ('etios liva gd', 'Etios Liva Gd'),
    ('venue s 1.0 turbo imt', 'Venue S 1.0 Turbo Imt'),
    ('swift dzire vxi', 'Swift Dzire Vxi'),
    ('sonet htx anniversary edition 1.0 imt', 'Sonet Htx Anniversary Edition 1.0 Imt'),
    ('kwid climber 1.0', 'Kwid Climber 1.0'),
    ('dzire vxi', 'Dzire Vxi'),
    ('ignis delta 1.2', 'Ignis Delta 1.2'),
    ('polo highline1.5l', 'Polo Highline1.5L'),
    ('seltos gtx 1.4 petrol', 'Seltos Gtx 1.4 Petrol'),
    ('dzire zxi amt', 'Dzire Zxi Amt'),
    ('ciaz zxi at', 'Ciaz Zxi At'),
    ('rapid 1.6 mpi active', 'Rapid 1.6 Mpi Active'),
    ('etios g', 'Etios G'),
    ('seltos gtx plus dct 1.4 petrol', 'Seltos Gtx Plus Dct 1.4 Petrol'),
    ('verna 1.6 vtvt sx o', 'Verna 1.6 Vtvt Sx O'),
    ('dzire vdi amt', 'Dzire Vdi Amt'),
    ('ciaz vdi shvs', 'Ciaz Vdi Shvs'),
    ('i10 sportz 1.2', 'I10 Sportz 1.2'),
    ('aura sx plus 1.2 amt', 'Aura Sx Plus 1.2 Amt'),
    ('tucson 2wd mt petrol', 'Tucson 2Wd Mt Petrol'),
    ('duster rxs cvt', 'Duster Rxs Cvt'),
    ('ciaz vxi+', 'Ciaz Vxi+'),
    ('ignis zeta 1.2 amt', 'Ignis Zeta 1.2 Amt'),
    ('nano twist xta', 'Nano Twist Xta'),
    ('xuv500 w9', 'Xuv500 W9'),
    ('seltos htk 1.5 diesel', 'Seltos Htk 1.5 Diesel'),
    ('elite i20 asta 1.2 dual tone', 'Elite I20 Asta 1.2 Dual Tone'),
    ('seltos htk plus 1.5', 'Seltos Htk Plus 1.5'),
    ('ecosport titanium 1.5l diesel', 'Ecosport Titanium 1.5L Diesel'),
    ('harrier xza plus 2.0l', 'Harrier Xza Plus 2.0L'),
    ('hector plus sharp 1.5 petrol turbo dct 6-str', 'Hector Plus Sharp 1.5 Petrol Turbo Dct 6-Str'),
    ('xuv500 w7', 'Xuv500 W7'),
    ('verna sx (o) 1.0 turbo dct', 'Verna Sx (O) 1.0 Turbo Dct'),
    ('dzire zxi', 'Dzire Zxi'),
    ('sonet gtx plus 1.0 imt', 'Sonet Gtx Plus 1.0 Imt'),
    ('s presso vxi plus (o) amt', 'S Presso Vxi Plus (O) Amt'),
    ('alto 800 vxi o', 'Alto 800 Vxi O'),
    ('grand i10 sportz 1.1 crdi', 'Grand I10 Sportz 1.1 Crdi'),
    ('vitara brezza vdi amt', 'Vitara Brezza Vdi Amt'),
    ('polo comfortline 1.0l mpi', 'Polo Comfortline 1.0L Mpi'),
    ('new santro sportz mt', 'New Santro Sportz Mt'),
    ('celerio zxi amt (o)', 'Celerio Zxi Amt (O)'),
    ('wr-v 1.2l i-vtec vx mt', 'Wr-V 1.2L I-Vtec Vx Mt'),
    ('swift lxi (o)', 'Swift Lxi (O)'),
    ('new wagon-r zxi 1.2 amt', 'New Wagon-R Zxi 1.2 Amt'),
    ('new wagon-r vxi 1.0 amt', 'New Wagon-R Vxi 1.0 Amt'),
    ('wagon r 1.0 lx', 'Wagon R 1.0 Lx'),
    ('sonet htx plus 1.0 imt', 'Sonet Htx Plus 1.0 Imt'),
    ('new i20 asta 1.2 at', 'New I20 Asta 1.2 At'),
    ('seltos gtx plus 1.4 petrol', 'Seltos Gtx Plus 1.4 Petrol'),
    ('alto lxi o', 'Alto Lxi O'),
    ('tiago xza petrol', 'Tiago Xza Petrol'),
    ('dzire vxi amt', 'Dzire Vxi Amt'),
    ('seltos hte 1.5 diesel', 'Seltos Hte 1.5 Diesel'),
    ('etios vx', 'Etios Vx'),
    ('bolero b6 (o)', 'Bolero B6 (O)'),
    ('magnite xv executive turbo cvt', 'Magnite Xv Executive Turbo Cvt'),
    ('dzire zxi plus amt', 'Dzire Zxi Plus Amt'),
    ('jazz 1.2l i-vtec v', 'Jazz 1.2L I-Vtec V'),
    ('baleno zeta petrol 1.2', 'Baleno Zeta Petrol 1.2'),
    ('grand i10 magna 1.2 kappa vtvt', 'Grand I10 Magna 1.2 Kappa Vtvt'),
    ('grand i10 sportz at 1.2 kappa vtvt', 'Grand I10 Sportz At 1.2 Kappa Vtvt'),
    ('verna fluidic 4s 1.6 vtvt s(o)', 'Verna Fluidic 4S 1.6 Vtvt S(O)'),
    ('city 1.5l i-vtec zx', 'City 1.5L I-Vtec Zx'),
    ('new wagon-r vxi (o) 1.2 amt', 'New Wagon-R Vxi (O) 1.2 Amt'),
    ('verna 1.6 vtvt sx', 'Verna 1.6 Vtvt Sx'),
    ('kwid climber 1.0 amt (o)', 'Kwid Climber 1.0 Amt (O)'),
    ('nexon xza plus diesel', 'Nexon Xza Plus Diesel'),
    ('new wagon-r lxi cng 1.0', 'New Wagon-R Lxi Cng 1.0'),
    ('magnite xv premium dual tone', 'Magnite Xv Premium Dual Tone'),
    ('magnite xv premium turbo cvt', 'Magnite Xv Premium Turbo Cvt'),
    ('dzire zxi plus amt', 'Dzire Zxi Plus Amt'),
    ('new i20 asta (o) 1.2 mt', 'New I20 Asta (O) 1.2 Mt'),
    ('elite i20 asta 1.2 (o)', 'Elite I20 Asta 1.2 (O)'),
    ('tiago xz plus petrol', 'Tiago Xz Plus Petrol'),
    ('city 1.5l i-vtec sv cvt', 'City 1.5L I-Vtec Sv Cvt'),
    ('wagon r 1.0 lxi cng', 'Wagon R 1.0 Lxi Cng'),
    ('ecosport titanium+ 1.5l diesel', 'Ecosport Titanium+ 1.5L Diesel'),
    ('xuv700 ax 5 p mt 5 str', 'Xuv700 Ax 5 P Mt 5 Str'),
    ('nexon xz plus (l)', 'Nexon Xz Plus (L)'),
    ('alto vxi plus', 'Alto Vxi Plus'),
    ('thar lx petrol ht 4wd at', 'Thar Lx Petrol Ht 4Wd At'),
    ('harrier xza plus 2.0l dual tone', 'Harrier Xza Plus 2.0L Dual Tone'),
    ('swift zxi plus', 'Swift Zxi Plus'),
    ('yaris g mt', 'Yaris G Mt'),
    ('tiago nrg petrol', 'Tiago Nrg Petrol'),
    ('nexon xma diesel', 'Nexon Xma Diesel'),
    ('duster 85 ps rxe diesel adventure', 'Duster 85 Ps Rxe Diesel Adventure'),
    ('swift dzire zxi', 'Swift Dzire Zxi'),
    ('duster 85 ps rxs mt diesel', 'Duster 85 Ps Rxs Mt Diesel'),
    ('seltos gtx plus at 1.5 diesel', 'Seltos Gtx Plus At 1.5 Diesel'),
    ('new wagon-r zxi 1.2', 'New Wagon-R Zxi 1.2'),
    ('etios liva g', 'Etios Liva G'),
    ('i20 magna (o) 1.2', 'I20 Magna (O) 1.2'),
    ('grand i10 nios magna corporate edition 1.2 kappa vtvt', 'Grand I10 Nios Magna Corporate Edition 1.2 Kappa Vtvt'),
    ('glanza g cvt', 'Glanza G Cvt'),
    ('creta sx 1.6 diesel', 'Creta Sx 1.6 Diesel'),
    ('xuv300 w8 (o) 1.2 petrol amt', 'Xuv300 W8 (O) 1.2 Petrol Amt'),
    ('creta sx 1.5 petrol', 'Creta Sx 1.5 Petrol'),
    ('elite i20 sportz plus 1.2', 'Elite I20 Sportz Plus 1.2'),
    ('baleno delta cvt petrol 1.2', 'Baleno Delta Cvt Petrol 1.2'),
    ('sonet gtx plus 1.5d  at', 'Sonet Gtx Plus 1.5D  At'),
    ('elite i20 asta 1.4 crdi (o)', 'Elite I20 Asta 1.4 Crdi (O)'),
    ('hector sharp 2.0 diesel', 'Hector Sharp 2.0 Diesel'),
    ('sonet htk plus 1.5', 'Sonet Htk Plus 1.5'),
    ('xl6 zeta at', 'Xl6 Zeta At'),
    ('alto k10 vxi plus amt', 'Alto K10 Vxi Plus Amt'),
    ('new i20 sportz 1.2 mt', 'New I20 Sportz 1.2 Mt'),
    ('glanza v cvt', 'Glanza V Cvt'),
    ('vitara brezza zxi plus', 'Vitara Brezza Zxi Plus'),
    ('new santro sportz amt', 'New Santro Sportz Amt'),
    ('ignis zeta 1.2', 'Ignis Zeta 1.2'),
    ('grand i10 nios sportz amt 1.2 kappa vtvt', 'Grand I10 Nios Sportz Amt 1.2 Kappa Vtvt'),
    ('redi go t (o)', 'Redi Go T (O)'),
    ('wagon r 1.0 lxi', 'Wagon R 1.0 Lxi'),
    ('alto 800 vxi', 'Alto 800 Vxi'),
    ('altroz xz petrol', 'Altroz Xz Petrol'),
    ('xuv500 w6', 'Xuv500 W6'),
    ('ertiga vdi', 'Ertiga Vdi'),
    ('ciaz zxi', 'Ciaz Zxi'),
    ('punch accomplished amt', 'Punch Accomplished Amt'),
    ('nexon xe petrol', 'Nexon Xe Petrol'),
    ('alto lxi', 'Alto Lxi'),
    ('alto k10 vxi amt', 'Alto K10 Vxi Amt'),
    ('triber rxz', 'Triber Rxz'),
    ('seltos htx ivt 1.5 petrol', 'Seltos Htx Ivt 1.5 Petrol'),
    ('xuv500 w9 at', 'Xuv500 W9 At'),
    ('ertiga vxi shvs', 'Ertiga Vxi Shvs'),
    ('sonet htx 1.5', 'Sonet Htx 1.5'),
    ('i10 asta 1.2', 'I10 Asta 1.2'),
    ('creta sx at 1.6 diesel', 'Creta Sx At 1.6 Diesel'),
    ('eon magna +', 'Eon Magna +'),
    ('alto 800 lxi cng o', 'Alto 800 Lxi Cng O'),
    ('jazz 1.2l i-vtec s', 'Jazz 1.2L I-Vtec S'),
    ('venue sx 1.0 turbo imt', 'Venue Sx 1.0 Turbo Imt'),
    ('duster 110 ps rxl 4x2 amt', 'Duster 110 Ps Rxl 4X2 Amt'),
    ('brio v mt', 'Brio V Mt'),
    ('tiago xz petrol', 'Tiago Xz Petrol'),
    ('celerio zxi amt', 'Celerio Zxi Amt'),
    ('verna fluidic 4s 1.6 vtvt s', 'Verna Fluidic 4S 1.6 Vtvt S'),
    ('punch creative  mt', 'Punch Creative  Mt'),
    ('wagon r 1.0 vxi + (o) amt', 'Wagon R 1.0 Vxi + (O) Amt'),
    ('creta sx (o) 1.6 diesel', 'Creta Sx (O) 1.6 Diesel'),
    ('creta sx (o) 1.4 turbo dct', 'Creta Sx (O) 1.4 Turbo Dct'),
    ('tiago xm petrol', 'Tiago Xm Petrol'),
    ('triber rxl mt', 'Triber Rxl Mt'),
    ('xuv500 w11 at', 'Xuv500 W11 At'),
    ('ecosport trend + 1.5l petrol at', 'Ecosport Trend + 1.5L Petrol At'),
    ('ameo highline1.5l', 'Ameo Highline1.5L'),
    ('xl6 zeta mt', 'Xl6 Zeta Mt'),
    ('verna 1.6 vtvt sx (o) at', 'Verna 1.6 Vtvt Sx (O) At'),
    ('tuv300 t8', 'Tuv300 T8'),
    ('sonet gtx plus 1.0 imt dual tone', 'Sonet Gtx Plus 1.0 Imt Dual Tone'),
    ('amaze 1.2l i-vtec sx', 'Amaze 1.2L I-Vtec Sx'),
    ('new i20 asta 1.2 mt', 'New I20 Asta 1.2 Mt'),
    ('glanza e', 'Glanza E'),
    ('sonet htx plus 1.5', 'Sonet Htx Plus 1.5'),
    ('xuv300 w8 (o) 1.5 diesel amt', 'Xuv300 W8 (O) 1.5 Diesel Amt'),
    ('grand i10 era 1.2 kappa vtvt', 'Grand I10 Era 1.2 Kappa Vtvt'),
    ('nexon xz plus diesel sunroof', 'Nexon Xz Plus Diesel Sunroof'),
    ('go t(o)', 'Go T(O)'),
    ('celerio zxi', 'Celerio Zxi'),
    ('city 1.5l i-vtec sv', 'City 1.5L I-Vtec Sv'),
    ('creta sx plus at 1.6 diesel', 'Creta Sx Plus At 1.6 Diesel'),
    ('grand i10 magna at 1.2 kappa vtvt', 'Grand I10 Magna At 1.2 Kappa Vtvt'),
    ('xcent e+', 'Xcent E+'),
    ('seltos htx 1.5 petrol', 'Seltos Htx 1.5 Petrol'),
    ('seltos gtx (o) 1.4', 'Seltos Gtx (O) 1.4'),
    ('wr-v 1.5l i-dtec vx mt', 'Wr-V 1.5L I-Dtec Vx Mt'),
    ('celerio vxi amt (o)', 'Celerio Vxi Amt (O)'),
    ('grand i10 sportz (o) at 1.2 kappa vtvt', 'Grand I10 Sportz (O) At 1.2 Kappa Vtvt'),
    ('nexon creative plus s 1.2 revotron 6 amt dt', 'Nexon Creative Plus S 1.2 Revotron 6 Amt Dt'),
    ('go plus a(o)', 'Go Plus A(O)'),
    ('verna sx 1.5 crdi', 'Verna Sx 1.5 Crdi'),
    ('ritz vdi', 'Ritz Vdi'),
    ('i10 magna 1.1', 'I10 Magna 1.1'),
    ('grand vitara delta smart hybrid', 'Grand Vitara Delta Smart Hybrid'),
    ('alto k10 lxi', 'Alto K10 Lxi'),
    ('nexon xz plus petrol', 'Nexon Xz Plus Petrol'),
    ('wagon r stingray vxi', 'Wagon R Stingray Vxi'),
    ('seltos htk plus at 1.5 diesel', 'Seltos Htk Plus At 1.5 Diesel'),
    ('carens luxury plus 1.4 petrol 7 str', 'Carens Luxury Plus 1.4 Petrol 7 Str'),
    ('seltos htx plus 1.5 diesel', 'Seltos Htx Plus 1.5 Diesel'),
    ('grand i10 nios sportz 1.2 kappa vtvt cng', 'Grand I10 Nios Sportz 1.2 Kappa Vtvt Cng'),
    ('kwid 1.0 marvel iron man edition amt', 'Kwid 1.0 Marvel Iron Man Edition Amt'),
    ('ciaz vxi', 'Ciaz Vxi'),
    ('baleno zeta 1.2 ags', 'Baleno Zeta 1.2 Ags'),
    ('kwid 1.0 marvel iron man edition', 'Kwid 1.0 Marvel Iron Man Edition'),
    ('tiago xza plus petrol', 'Tiago Xza Plus Petrol'),
    ('city 1.5l i-vtec s mt', 'City 1.5L I-Vtec S Mt'),
    ('vitara brezza vxi at shvs', 'Vitara Brezza Vxi At Shvs'),
    ('xuv700 ax 7 luxury d awd at 7 str', 'Xuv700 Ax 7 Luxury D Awd At 7 Str'),
    ('altroz xe petrol', 'Altroz Xe Petrol'),
    ('nexon xz plus (o) petrol dark edition', 'Nexon Xz Plus (O) Petrol Dark Edition'),
    ('s presso vxi amt', 'S Presso Vxi Amt'),
    ('grand i10 sportz (o) 1.2 kappa vtvt', 'Grand I10 Sportz (O) 1.2 Kappa Vtvt'),
    ('creta s 1.6 petrol', 'Creta S 1.6 Petrol'),
    ('new santro asta mt', 'New Santro Asta Mt'),
    ('rapid ambition 1.6 mpi mt', 'Rapid Ambition 1.6 Mpi Mt'),
    ('nexon ev xm', 'Nexon Ev Xm'),
    ('i20 active 1.2 sx', 'I20 Active 1.2 Sx'),
    ('etios cross 1.4 gd', 'Etios Cross 1.4 Gd'),
    ('ecosport trend 1.5l petrol', 'Ecosport Trend 1.5L Petrol'),
    ('xuv300 w6 1.2 petrol amt', 'Xuv300 W6 1.2 Petrol Amt'),
    ('go plus t (o)', 'Go Plus T (O)'),
    ('alto k10 vxi (o)', 'Alto K10 Vxi (O)'),
    ('nexon ev xz plus', 'Nexon Ev Xz Plus'),
    ('safari xma', 'Safari Xma'),
    ('glanza v', 'Glanza V'),
    ('celerio zxi plus ags', 'Celerio Zxi Plus Ags'),
    ('i20 magna 1.2', 'I20 Magna 1.2'),
    ('ertiga zxi', 'Ertiga Zxi'),
    ('xuv300 w8 (o) 1.2 petrol', 'Xuv300 W8 (O) 1.2 Petrol'),
    ('s presso vxi (o)', 'S Presso Vxi (O)'),
    ('xuv300 w4 1.5 diesel', 'Xuv300 W4 1.5 Diesel'),
    ('ciaz delta at 1.5 shvs petrol', 'Ciaz Delta At 1.5 Shvs Petrol'),
    ('new wagon-r vxi cng 1.0', 'New Wagon-R Vxi Cng 1.0'),
    ('creta s 1.5 petrol', 'Creta S 1.5 Petrol'),
    ('elite i20 magna 1.2', 'Elite I20 Magna 1.2'),
    ('kwid rxl 1.0 (o)', 'Kwid Rxl 1.0 (O)'),
    ('city 1.5l i-vte v cvt', 'City 1.5L I-Vte V Cvt'),
    ('zest xt petrol', 'Zest Xt Petrol'),
    ('verna fluidic 1.6 vtvt ex', 'Verna Fluidic 1.6 Vtvt Ex'),
    ('venue s(o) 1.2', 'Venue S(O) 1.2'),
    ('duster rxs opt cvt', 'Duster Rxs Opt Cvt'),
    ('ciaz delta 1.5 shvs mt petrol', 'Ciaz Delta 1.5 Shvs Mt Petrol'),
    ('nexon xza plus (o) petrol dark edition', 'Nexon Xza Plus (O) Petrol Dark Edition'),
    ('kwid neotech rxl 1.0 amt', 'Kwid Neotech Rxl 1.0 Amt'),
    ('baleno zeta diesel 1.3', 'Baleno Zeta Diesel 1.3'),
    ('triber rxt', 'Triber Rxt'),
    ('xcent sx 1.2 (o)', 'Xcent Sx 1.2 (O)'),
    ('xuv700 ax 7 p mt 7 str', 'Xuv700 Ax 7 P Mt 7 Str'),
    ('xcent prime 	t+ cng', 'Xcent Prime 	T+ Cng'),
    ('thar lx d 4wd at convertible', 'Thar Lx D 4Wd At Convertible'),
    ('alto lxi opt cng', 'Alto Lxi Opt Cng'),
    ('magnite xl turbo cvt', 'Magnite Xl Turbo Cvt'),
    ('i20 sportz (o) 1.2', 'I20 Sportz (O) 1.2'),
    ('redi go s 1.0 amt', 'Redi Go S 1.0 Amt'),
    ('vento highline 1.5 at', 'Vento Highline 1.5 At'),
    ('tigor xz (o) petrol', 'Tigor Xz (O) Petrol'),
    ('hector super 1.5 petrol', 'Hector Super 1.5 Petrol'),
    ('brio vx at', 'Brio Vx At'),
    ('ertiga zxi at shvs', 'Ertiga Zxi At Shvs'),
    ('swift zxi plus amt dual tone', 'Swift Zxi Plus Amt Dual Tone'),
    ('ertiga zxi+ shvs', 'Ertiga Zxi+ Shvs'),
    ('ciaz delta 1.4 at petrol', 'Ciaz Delta 1.4 At Petrol'),
    ('brezza zxi smart hybrid', 'Brezza Zxi Smart Hybrid'),
    ('new i20 n line n8 1.0 turbo gdi imt', 'New I20 N Line N8 1.0 Turbo Gdi Imt'),
    ('wagon r 1.0 vxi amt', 'Wagon R 1.0 Vxi Amt'),
    ('magnite xv mt', 'Magnite Xv Mt'),
    ('ritz vxi', 'Ritz Vxi'),
    ('rapid style 1.6 mpi at', 'Rapid Style 1.6 Mpi At'),
    ('tiago xt petrol', 'Tiago Xt Petrol'),
    ('ciaz alpha diesel 1.5', 'Ciaz Alpha Diesel 1.5'),
    ('ameo highline1.2l', 'Ameo Highline1.2L'),
    ('ameo highline plus 1.0l 16 alloy', 'Ameo Highline Plus 1.0L 16 Alloy'),
    ('i10 sportz 1.1', 'I10 Sportz 1.1'),
    ('swift vxi o', 'Swift Vxi O'),
    ('kwid rxl 1.0', 'Kwid Rxl 1.0'),
    ('dzire lxi', 'Dzire Lxi'),
    ('verna sx (o) 1.5 crdi', 'Verna Sx (O) 1.5 Crdi'),
    ('carens luxury plus 1.4 petrol 6 str', 'Carens Luxury Plus 1.4 Petrol 6 Str'),
    ('ertiga zdi', 'Ertiga Zdi'),
    ('ecosport titanium 1.5 sports(sunroof) petrol', 'Ecosport Titanium 1.5 Sports(Sunroof) Petrol'),
    ('s presso vxi cng', 'S Presso Vxi Cng'),
    ('nexon xz petrol', 'Nexon Xz Petrol'),
    ('baleno alpha diesel 1.3', 'Baleno Alpha Diesel 1.3'),
    ('seltos gtk 1.4 petrol', 'Seltos Gtk 1.4 Petrol'),
    ('nexon xza plus sunroof petrol', 'Nexon Xza Plus Sunroof Petrol'),
    ('venue sx plus 1.0 turbo dct', 'Venue Sx Plus 1.0 Turbo Dct'),
    ('duster rxz 1.5 petrol mt', 'Duster Rxz 1.5 Petrol Mt'),
    ('punch creative  amt', 'Punch Creative  Amt'),
    ('sonet htk plus 1.2', 'Sonet Htk Plus 1.2'),
    ('taigun topline 1.0 tsi at', 'Taigun Topline 1.0 Tsi At'),
    ('xl6 alpha plus at', 'Xl6 Alpha Plus At'),
    ('jazz 1.2l i-vtec vx cvt', 'Jazz 1.2L I-Vtec Vx Cvt'),
    ('sonet gtx plus 1.5', 'Sonet Gtx Plus 1.5'),
    ('new santro era executive', 'New Santro Era Executive'),
    ('jazz 1.2l i-vtec vx', 'Jazz 1.2L I-Vtec Vx'),
    ('ecosport titanium + 1.5l petrol at', 'Ecosport Titanium + 1.5L Petrol At'),
    ('ertiga zdi + shvs', 'Ertiga Zdi + Shvs'),
    ('safari xza plus dark edition', 'Safari Xza Plus Dark Edition'),
    ('alto k10 vxi (o) amt', 'Alto K10 Vxi (O) Amt'),
    ('amaze 1.2l i-vtec v cvt', 'Amaze 1.2L I-Vtec V Cvt'),
    ('kwid climber 1.0 (o) dual tone', 'Kwid Climber 1.0 (O) Dual Tone'),
    ('harrier xt plus 2.0l kryotec dark editon', 'Harrier Xt Plus 2.0L Kryotec Dark Editon'),
    ('new i20 n line n6 1.0 turbo gdi imt', 'New I20 N Line N6 1.0 Turbo Gdi Imt'),
    ('swift zdi', 'Swift Zdi'),
    ('ciaz zxi+', 'Ciaz Zxi+'),
    ('ciaz alpha  at 1.4  petrol', 'Ciaz Alpha  At 1.4  Petrol'),
    ('tigor xe petrol', 'Tigor Xe Petrol'),
    ('hector savvy pro 1.5 turbo cvt petrol', 'Hector Savvy Pro 1.5 Turbo Cvt Petrol'),
    ('ameo trendline 1.0l', 'Ameo Trendline 1.0L'),
    ('go plus t(o)', 'Go Plus T(O)'),
    ('brio s(o) mt', 'Brio S(O) Mt'),
    ('verna 1.6 crdi sx', 'Verna 1.6 Crdi Sx'),
    ('polo gt tsi at', 'Polo Gt Tsi At'),
    ('magnite xl turbo', 'Magnite Xl Turbo'),
    ('aura sx plus 1.2 amt crdi', 'Aura Sx Plus 1.2 Amt Crdi'),
    ('polo highline plus 1.5', 'Polo Highline Plus 1.5'),
    ('sonet htk plus 1.0 imt', 'Sonet Htk Plus 1.0 Imt'),
    ('i10 era 1.1', 'I10 Era 1.1'),
    ('ertiga vxi at shvs', 'Ertiga Vxi At Shvs'),
    ('wagon r 1.0 vxi+ (o) mt', 'Wagon R 1.0 Vxi+ (O) Mt'),
    ('ciaz sigma 1.5 shvs mt  petrol', 'Ciaz Sigma 1.5 Shvs Mt  Petrol'),
    ('aura s 1.2 cng', 'Aura S 1.2 Cng'),
    ('grand i10 nios sportz 1.2 kappa vtvt', 'Grand I10 Nios Sportz 1.2 Kappa Vtvt'),
    ('ecosport titanium 1.5l petrol', 'Ecosport Titanium 1.5L Petrol'),
    ('alto 800 lxi o', 'Alto 800 Lxi O'),
    ('brio vx mt', 'Brio Vx Mt'),
    ('xcent sx 1.2', 'Xcent Sx 1.2'),
    ('s presso vxi', 'S Presso Vxi'),
    ('compass sport plus 1.4 petrol', 'Compass Sport Plus 1.4 Petrol'),
    ('duster 110 ps rxz 4x2 amt diesel', 'Duster 110 Ps Rxz 4X2 Amt Diesel'),
    ('ertiga vxi cng', 'Ertiga Vxi Cng'),
    ('freestyle titanium 1.2 petrol', 'Freestyle Titanium 1.2 Petrol'),
    ('safari xza plus gold 6 s', 'Safari Xza Plus Gold 6 S'),
    ('polo trendline 1.0l', 'Polo Trendline 1.0L'),
    ('tiago xt cng', 'Tiago Xt Cng'),
    ('zest xta f-tronic diesel', 'Zest Xta F-Tronic Diesel'),
    ('new i20 sportz 1.2 ivt', 'New I20 Sportz 1.2 Ivt'),
    ('verna sx 1.5 vtvt ivt', 'Verna Sx 1.5 Vtvt Ivt'),
    ('br-v 1.5l i-vtec s', 'Br-V 1.5L I-Vtec S'),
    ('seltos htk plus 1.5 diesel', 'Seltos Htk Plus 1.5 Diesel'),
    ('br-v 1.5l i-vtec vx', 'Br-V 1.5L I-Vtec Vx'),
    ('polo highline1.2l', 'Polo Highline1.2L'),
    ('civic 1.8l i-vtec zx cvt', 'Civic 1.8L I-Vtec Zx Cvt'),
    ('amaze 1.2l i-vtec vx cvt', 'Amaze 1.2L I-Vtec Vx Cvt'),
    ('swift vdi (o)', 'Swift Vdi (O)'),
    ('kwid rxl', 'Kwid Rxl'),
    ('amaze 1.2l i-vtec e', 'Amaze 1.2L I-Vtec E'),
    ('xl6 alpha mt', 'Xl6 Alpha Mt'),
    ('eon era +', 'Eon Era +'),
    ('kushaq style 1.5l tsi mt', 'Kushaq Style 1.5L Tsi Mt'),
    ('tiago xz plus cng', 'Tiago Xz Plus Cng'),
    ('creta e 1.5 petrol', 'Creta E 1.5 Petrol'),
    ('venue sx 1.0 (o) turbo imt', 'Venue Sx 1.0 (O) Turbo Imt'),
    ('rapid style 1.5 tdi at', 'Rapid Style 1.5 Tdi At'),
    ('redi go s 1.0', 'Redi Go S 1.0'),
    ('carens premium 1.4 petrol 7 str', 'Carens Premium 1.4 Petrol 7 Str'),
    ('i10 asta 1.2 at sunroof', 'I10 Asta 1.2 At Sunroof'),
    ('i10 sportz 1.2 at', 'I10 Sportz 1.2 At'),
    ('sonet x line 1.0 dct', 'Sonet X Line 1.0 Dct'),
    ('dzire zxi plus', 'Dzire Zxi Plus'),
    ('new santro magna amt', 'New Santro Magna Amt'),
    ('tigor xza plus petrol', 'Tigor Xza Plus Petrol'),
    ('creta ex 1.5 petrol', 'Creta Ex 1.5 Petrol'),
    ('xuv300 w8(o) 1.2 petrol dual tone', 'Xuv300 W8(O) 1.2 Petrol Dual Tone'),
    ('creta ex 1.6 petrol', 'Creta Ex 1.6 Petrol'),
    ('amaze 1.5l i-dtec v', 'Amaze 1.5L I-Dtec V'),
    ('new santro magna', 'New Santro Magna'),
    ('elite i20 sportz plus 1.2 dual tone', 'Elite I20 Sportz Plus 1.2 Dual Tone'),
    ('ertiga zxi+', 'Ertiga Zxi+'),
    ('celerio vxi', 'Celerio Vxi'),
    ('verna fluidic 1.6 vtvt sx', 'Verna Fluidic 1.6 Vtvt Sx'),
    ('nexon xm plus sunroof petrol', 'Nexon Xm Plus Sunroof Petrol'),
    ('nexon xza plus diesel kaziranga', 'Nexon Xza Plus Diesel Kaziranga'),
    ('compass sport 1.4 petrol', 'Compass Sport 1.4 Petrol'),
    ('glanza v amt', 'Glanza V Amt'),
    ('triber rxl amt', 'Triber Rxl Amt'),
    ('vento highline petrol at', 'Vento Highline Petrol At'),
    ('vento highline plus 1.2 at', 'Vento Highline Plus 1.2 At'),
    ('nexon xz plus sunroof petrol dual tone', 'Nexon Xz Plus Sunroof Petrol Dual Tone'),
    ('tigor xz plus cng', 'Tigor Xz Plus Cng'),
    ('redi go t(o) 1.0 amt', 'Redi Go T(O) 1.0 Amt'),
    ('ertiga zxi+ at shvs', 'Ertiga Zxi+ At Shvs'),
    ('duster 85 ps rxl diesel', 'Duster 85 Ps Rxl Diesel'),
    ('vento highline plus 1.2 at 16 alloy', 'Vento Highline Plus 1.2 At 16 Alloy'),
    ('magnite xv turbo', 'Magnite Xv Turbo'),
    ('kwid climber amt 1.0', 'Kwid Climber Amt 1.0'),
    ('altroz xz plus diesel', 'Altroz Xz Plus Diesel'),
    ('ciaz zeta 1.4  at petrol', 'Ciaz Zeta 1.4  At Petrol'),
    ('glanza g', 'Glanza G'),
    ('nexon xm sunroof diesel', 'Nexon Xm Sunroof Diesel'),
    ('verna 1.6 vtvt sx at', 'Verna 1.6 Vtvt Sx At'),
    ('etios v', 'Etios V'),
    ('wr-v 1.2l i-vtec s mt', 'Wr-V 1.2L I-Vtec S Mt'),
    ('rapid ambition 1.5 tdi', 'Rapid Ambition 1.5 Tdi'),
    ('carens luxury plus 1.5 diesel at 7 str', 'Carens Luxury Plus 1.5 Diesel At 7 Str'),
    ('duster 110 ps rxl diesel', 'Duster 110 Ps Rxl Diesel'),
    ('safari xza plus', 'Safari Xza Plus'),
    ('duster rxl petrol', 'Duster Rxl Petrol'),
    ('duster 110 ps rxz diesel plus', 'Duster 110 Ps Rxz Diesel Plus'),
    ('kushaq monte carlo 1.5l tsi dsg', 'Kushaq Monte Carlo 1.5L Tsi Dsg'),
    ('tiago nrg xz amt', 'Tiago Nrg Xz Amt'),
    ('amaze 1.5l i-dtec vx cvt', 'Amaze 1.5L I-Dtec Vx Cvt'),
    ('vitara brezza zxi', 'Vitara Brezza Zxi'),
    ('seltos gtx plus 1.5 diesel at', 'Seltos Gtx Plus 1.5 Diesel At'),
    ('ciaz zxi+ at', 'Ciaz Zxi+ At'),
    ('tigor xm petrol', 'Tigor Xm Petrol'),
    ('freestyle titanium plus 1.2 petrol', 'Freestyle Titanium Plus 1.2 Petrol'),
    ('rapid style 1.6 mpi', 'Rapid Style 1.6 Mpi'),
    ('slavia style 1.0l tsi at', 'Slavia Style 1.0L Tsi At'),
    ('rapid ambition at tsi', 'Rapid Ambition At Tsi'),
    ('new wagon-r vxi (o) 1.2', 'New Wagon-R Vxi (O) 1.2'),
    ('kiger rxl mt', 'Kiger Rxl Mt'),
    ('thar lx d 4*4 mt ht', 'Thar Lx D 4*4 Mt Ht'),
    ('kuv100 k4 6 str', 'Kuv100 K4 6 Str'),
    ('urban cruiser mid grade mt', 'Urban Cruiser Mid Grade Mt'),
    ('hector plus sharp 2.0 diesel turbo mt 6-str dual tone', 'Hector Plus Sharp 2.0 Diesel Turbo Mt 6-Str Dual Tone'),
    ('verna fluidic 1.6 crdi sx', 'Verna Fluidic 1.6 Crdi Sx'),
    ('tiago xt (o) petrol', 'Tiago Xt (O) Petrol'),
    ('redi go s', 'Redi Go S'),
    ('ignis zeta 1.2 amt dual tone', 'Ignis Zeta 1.2 Amt Dual Tone'),
    ('sonet htx anniversary edition 1.5', 'Sonet Htx Anniversary Edition 1.5'),
    ('nexon xm petrol', 'Nexon Xm Petrol'),
    ('micra xv cvt', 'Micra Xv Cvt'),
    ('s cross zeta 1.3', 'S Cross Zeta 1.3'),
    ('xuv700 mx p mt 5 str', 'Xuv700 Mx P Mt 5 Str'),
    ('xuv700 ax 3 d at 5 str', 'Xuv700 Ax 3 D At 5 Str'),
    ('verna sx (o) 1.5 vtvt ivt', 'Verna Sx (O) 1.5 Vtvt Ivt'),
    ('jazz 1.2l i-vtec sv', 'Jazz 1.2L I-Vtec Sv'),
    ('punch creative ira amt 1.2 rtn dual tone', 'Punch Creative Ira Amt 1.2 Rtn Dual Tone'),
    ('kwid rxt 1.0 amt', 'Kwid Rxt 1.0 Amt'),
    ('grand i10 nios magna 1.2 kappa vtvt', 'Grand I10 Nios Magna 1.2 Kappa Vtvt'),
    ('celerio zxi plus', 'Celerio Zxi Plus'),
    ('alto k10 vxi plus', 'Alto K10 Vxi Plus'),
    ('swift vdi abs', 'Swift Vdi Abs'),
    ('kiger rxz turbo mt', 'Kiger Rxz Turbo Mt'),
    ('triber rxt amt', 'Triber Rxt Amt'),
    ('venue sx (o) 1.0 turbo dct', 'Venue Sx (O) 1.0 Turbo Dct'),
    ('xuv500 w5', 'Xuv500 W5'),
    ('vitara brezza vxi', 'Vitara Brezza Vxi'),
    ('ignis sigma 1.2', 'Ignis Sigma 1.2'),
    ('seltos htx anniversary edition 1.5 petrol', 'Seltos Htx Anniversary Edition 1.5 Petrol'),
    ('carens prestige 1.5 diesel 7 str', 'Carens Prestige 1.5 Diesel 7 Str'),
    ('tigor xz plus cng dual tone', 'Tigor Xz Plus Cng Dual Tone'),
    ('eon era', 'Eon Era'),
    ('compass limited plus diesel 4x4', 'Compass Limited Plus Diesel 4X4'),
    ('xuv700 ax 7 luxury d at 7 str', 'Xuv700 Ax 7 Luxury D At 7 Str'),
    ('alcazar 2.0 signature (o) at 7str', 'Alcazar 2.0 Signature (O) At 7Str'),
    ('br-v 1.5l i-vtec v cvt', 'Br-V 1.5L I-Vtec V Cvt'),
    ('sonet gtx plus 1.0 dct', 'Sonet Gtx Plus 1.0 Dct'),
    ('swift dzire vdi', 'Swift Dzire Vdi'),
    ('duster 85 ps rxz diesel', 'Duster 85 Ps Rxz Diesel'),
    ('vitara brezza zdi plus dual tone', 'Vitara Brezza Zdi Plus Dual Tone'),
    ('hector smart 1.5 dct petrol', 'Hector Smart 1.5 Dct Petrol'),
    ('xuv700 ax 5 p mt 7 str', 'Xuv700 Ax 5 P Mt 7 Str'),
    ('xuv500 w10 at', 'Xuv500 W10 At'),
    ('city 1.5l i-dtec v', 'City 1.5L I-Dtec V'),
    ('xuv700 ax 5 p at 5 str', 'Xuv700 Ax 5 P At 5 Str'),
    ('polo highline plus 1.0', 'Polo Highline Plus 1.0'),
    ('venue s+ 1.2', 'Venue S+ 1.2'),
    ('eon sportz', 'Eon Sportz'),
    ('creta base 1.6 petrol', 'Creta Base 1.6 Petrol'),
    ('amaze 1.2l i-vtec s cvt', 'Amaze 1.2L I-Vtec S Cvt'),
    ('safari xza plus 6s', 'Safari Xza Plus 6S'),
    ('magnite xv dual tone', 'Magnite Xv Dual Tone'),
    ('carens prestige 1.4 petrol 7 str', 'Carens Prestige 1.4 Petrol 7 Str'),
    ('celerio x zxi amt', 'Celerio X Zxi Amt'),
    ('harrier xz 2.0l', 'Harrier Xz 2.0L'),
    ('tiago xe petrol', 'Tiago Xe Petrol'),
    ('baleno delta diesel 1.3', 'Baleno Delta Diesel 1.3'),
    ('i20 asta 1.2', 'I20 Asta 1.2'),
    ('seltos htk plus 1.5 diesel imt', 'Seltos Htk Plus 1.5 Diesel Imt'),
    ('thar lx d 4wd mt convertible', 'Thar Lx D 4Wd Mt Convertible'),
    ('grand i10 sportz 1.2 kappa vtvt dual tone', 'Grand I10 Sportz 1.2 Kappa Vtvt Dual Tone'),
    ('kwid climber mt 1.0', 'Kwid Climber Mt 1.0'),
    ('tiago ev xt long range', 'Tiago Ev Xt Long Range'),
    ('xuv500 w11', 'Xuv500 W11'),
    ('jazz 1.2l i-vtec x', 'Jazz 1.2L I-Vtec X'),
    ('new i20 sportz (o) 1.2 ivt', 'New I20 Sportz (O) 1.2 Ivt'),
    ('amaze 1.2l i-vtec v', 'Amaze 1.2L I-Vtec V'),
    ('sonet htx 1.0 imt', 'Sonet Htx 1.0 Imt'),
    ('tigor xz plus cng leatherette pack', 'Tigor Xz Plus Cng Leatherette Pack'),
    ('jazz 1.2l i-vtec s at', 'Jazz 1.2L I-Vtec S At'),
    ('s presso vxi plus amt', 'S Presso Vxi Plus Amt'),
    ('elite i20 sportz plus  1.2 cvt', 'Elite I20 Sportz Plus  1.2 Cvt'),
    ('rapid ambition 1.6 mpi at', 'Rapid Ambition 1.6 Mpi At'),
    ('magnite xl', 'Magnite Xl'),
    ('ciaz zeta 1.5 shvs mt petrol', 'Ciaz Zeta 1.5 Shvs Mt Petrol'),
    ('redi go t(o)', 'Redi Go T(O)'),
    ('xuv300 w6 1.2 petrol', 'Xuv300 W6 1.2 Petrol'),
    ('creta sx (o) ivt 1.5 petrol', 'Creta Sx (O) Ivt 1.5 Petrol'),
    ('i20 asta 1.4 crdi', 'I20 Asta 1.4 Crdi'),
    ('swift dzire lxi', 'Swift Dzire Lxi'),
    ('compass limited plus petrol at', 'Compass Limited Plus Petrol At'),
    ('seltos htk 1.5 petrol', 'Seltos Htk 1.5 Petrol'),
    ('swift vxi abs', 'Swift Vxi Abs'),
    ('xuv500 w10 1.99', 'Xuv500 W10 1.99'),
    ('br-v 1.5l i-vtec e', 'Br-V 1.5L I-Vtec E'),
    ('xuv700 ax 5 d mt 5 str', 'Xuv700 Ax 5 D Mt 5 Str'),
    ('creta sx 1.6 petrol', 'Creta Sx 1.6 Petrol'),
    ('altroz xt petrol', 'Altroz Xt Petrol'),
    ('nexon xza plus sunroof diesel', 'Nexon Xza Plus Sunroof Diesel'),
    ('kiger rxz amt', 'Kiger Rxz Amt'),
    ('kushaq style 1.5l tsi dsg (6 airbags)', 'Kushaq Style 1.5L Tsi Dsg (6 Airbags)'),
    ('xl6 zeta cng', 'Xl6 Zeta Cng'),
    ('go plus t', 'Go Plus T'),
    ('freestyle trend 1.5 diesel', 'Freestyle Trend 1.5 Diesel'),
    ('brezza zxi  at smart hybrid dual tone', 'Brezza Zxi  At Smart Hybrid Dual Tone'),
    ('tigor xza petrol', 'Tigor Xza Petrol'),
    ('duster 110 ps rxl adventure', 'Duster 110 Ps Rxl Adventure'),
    ('civic 1.8l i-vtec v at', 'Civic 1.8L I-Vtec V At'),
    ('rapid ambition 1.6 mpi mt plus', 'Rapid Ambition 1.6 Mpi Mt Plus'),
    ('xuv300 w6 1.5 diesel', 'Xuv300 W6 1.5 Diesel'),
    ('i20 active 1.4 sx', 'I20 Active 1.4 Sx'),
    ('nexon xma petrol', 'Nexon Xma Petrol'),
    ('nexon xz plus diesel', 'Nexon Xz Plus Diesel'),
    ('triber rxe mt', 'Triber Rxe Mt'),
    ('innova crysta 2.7 vx 7 str', 'Innova Crysta 2.7 Vx 7 Str'),
    ('nexon xz plus (premium) petrol', 'Nexon Xz Plus (Premium) Petrol'),
    ('compass longitude plus 1.4 petrol at', 'Compass Longitude Plus 1.4 Petrol At'),
    ('corolla altis vl cvt petrol', 'Corolla Altis Vl Cvt Petrol'),
    ('safari xz plus 6s adventure', 'Safari Xz Plus 6S Adventure'),
    ('aura s 1.2', 'Aura S 1.2'),
    ('hector sharp pro 1.5 turbo mt petrol', 'Hector Sharp Pro 1.5 Turbo Mt Petrol'),
    ('xl6 alpha at', 'Xl6 Alpha At'),
    ('new wagon-r vxi 1.2 amt', 'New Wagon-R Vxi 1.2 Amt'),
    ('venue sx 1.2 petrol', 'Venue Sx 1.2 Petrol'),
    ('hector style 1.5 petrol', 'Hector Style 1.5 Petrol'),
    ('safari xz', 'Safari Xz'),
    ('new i20 asta (o) 1.2 at', 'New I20 Asta (O) 1.2 At'),
    ('yaris vx mt', 'Yaris Vx Mt'),
    ('elite i20 magna plus 1.2', 'Elite I20 Magna Plus 1.2'),
    ('xuv500 w7 at', 'Xuv500 W7 At'),
    ('baleno sigma petrol 1.2', 'Baleno Sigma Petrol 1.2'),
    ('thar lx p 2wd at ht', 'Thar Lx P 2Wd At Ht'),
    ('swift zxi plus amt', 'Swift Zxi Plus Amt'),
    ('s cross sigma 1.5', 'S Cross Sigma 1.5'),
    ('new i20 sportz 1.2 mt dual tone', 'New I20 Sportz 1.2 Mt Dual Tone'),
    ('kuv 100 nxt k2+ p 6 str', 'Kuv 100 Nxt K2+ P 6 Str'),
    ('magnite xv premium', 'Magnite Xv Premium'),
    ('swift zdi amt', 'Swift Zdi Amt'),
    ('terrano xl (d)', 'Terrano Xl (D)'),
    ('amaze 1.5l i-dtec v cvt', 'Amaze 1.5L I-Dtec V Cvt'),
    ('eon d-lite+', 'Eon D-Lite+'),
    ('safari xza plus adventure', 'Safari Xza Plus Adventure'),
    ('rapid 1.6 mpi style at', 'Rapid 1.6 Mpi Style At'),
    ('vitara brezza zxi plus at dual tone shvs', 'Vitara Brezza Zxi Plus At Dual Tone Shvs'),
    ('pulse rx l diesel', 'Pulse Rx L Diesel'),
    ('punch creative ira 1.2 rtn dual tone', 'Punch Creative Ira 1.2 Rtn Dual Tone'),
    ('safari xz plus dark edition', 'Safari Xz Plus Dark Edition'),
    ('vitara brezza zxi at shvs', 'Vitara Brezza Zxi At Shvs'),
    ('punch creative  ira pack mt', 'Punch Creative  Ira Pack Mt'),
    ('compass sport plus 2.0 diesel', 'Compass Sport Plus 2.0 Diesel'),
    ('venue s 1.0 turbo dct', 'Venue S 1.0 Turbo Dct'),
    ('duster 110 ps rxs 4x2 amt diesel', 'Duster 110 Ps Rxs 4X2 Amt Diesel'),
    ('virtus gt plus tsi 1.5 evo dsg', 'Virtus Gt Plus Tsi 1.5 Evo Dsg'),
    ('xl6 alpha plus mt', 'Xl6 Alpha Plus Mt'),
    ('ciaz zeta diesel 1.3', 'Ciaz Zeta Diesel 1.3'),
    ('ciaz delta diesel 1.3', 'Ciaz Delta Diesel 1.3'),
    ('grand i10 nios asta 1.2 kappa vtvt', 'Grand I10 Nios Asta 1.2 Kappa Vtvt'),
    ('punch adventure rhythm pack amt', 'Punch Adventure Rhythm Pack Amt'),
    ('compass longitude 2.0 diesel', 'Compass Longitude 2.0 Diesel'),
    ('seltos gtx plus 1.4', 'Seltos Gtx Plus 1.4'),
    ('seltos x line 1.4 dct', 'Seltos X Line 1.4 Dct'),
    ('carens prestige plus 1.4 petrol 7 str', 'Carens Prestige Plus 1.4 Petrol 7 Str'),
    ('new santro asta amt', 'New Santro Asta Amt'),
    ('amaze 1.5l i-dtec s cvt', 'Amaze 1.5L I-Dtec S Cvt'),
    ('micra xl petrol', 'Micra Xl Petrol'),
    ('slavia style 1.5l tsi dsg', 'Slavia Style 1.5L Tsi Dsg'),
    ('harrier xz plus 2.0l dark edition', 'Harrier Xz Plus 2.0L Dark Edition'),
    ('new i20 asta 1.0 gdi turbo imt', 'New I20 Asta 1.0 Gdi Turbo Imt'),
    ('s presso vxi (o) cng', 'S Presso Vxi (O) Cng'),
    ('aura sx 1.2 cng', 'Aura Sx 1.2 Cng'),
    ('nexon xza plus diesel (l)', 'Nexon Xza Plus Diesel (L)'),
    ('nexon xz plus petrol kaziranga', 'Nexon Xz Plus Petrol Kaziranga'),
    ('kushaq ambition 1.0l tsi at', 'Kushaq Ambition 1.0L Tsi At'),
    ('ciaz delta diesel 1.5', 'Ciaz Delta Diesel 1.5'),
    ('triber rxz dual tone', 'Triber Rxz Dual Tone'),
    ('freestyle titanium 1.5 diesel', 'Freestyle Titanium 1.5 Diesel'),
    ('magnite xv turbo cvt', 'Magnite Xv Turbo Cvt'),
    ('kwid rxl 1.0 amt', 'Kwid Rxl 1.0 Amt'),
    ('kushaq style 1.0l tsi mt', 'Kushaq Style 1.0L Tsi Mt'),
    ('baleno alpha 1.2 ags', 'Baleno Alpha 1.2 Ags'),
    ('nexon xz plus (premium) petrol jet', 'Nexon Xz Plus (Premium) Petrol Jet'),
    ('xl6 alpha plus  at dual tone', 'Xl6 Alpha Plus  At Dual Tone'),
    ('dzire zxi cng', 'Dzire Zxi Cng'),
    ('redi go t', 'Redi Go T'),
    ('hector sharp pro 1.5 petrol turbo cvt petrol', 'Hector Sharp Pro 1.5 Petrol Turbo Cvt Petrol'),
    ('creta sx ivt 1.5 petrol', 'Creta Sx Ivt 1.5 Petrol'),
    ('thar crde 4x4 ac', 'Thar Crde 4X4 Ac'),
    ('safari xza', 'Safari Xza'),
    ('altroz xza', 'Altroz Xza'),
    ('kushaq style 1.0l tsi at (6 airbags)', 'Kushaq Style 1.0L Tsi At (6 Airbags)'),
    ('nexon xza plus kaziranga petrol', 'Nexon Xza Plus Kaziranga Petrol'),
    ('brio ex mt', 'Brio Ex Mt'),
    ('ritz zdi', 'Ritz Zdi'),
    ('swift vdi', 'Swift Vdi'),
    ('elite i20 sportz plus 1.4 crdi', 'Elite I20 Sportz Plus 1.4 Crdi'),
    ('xcent sx at 1.2 (o)', 'Xcent Sx At 1.2 (O)'),
    ('aura sx 1.2 (o)', 'Aura Sx 1.2 (O)'),
    ('tigor xz cng', 'Tigor Xz Cng'),
    ('altroz xz plus i-turbo petrol dark edition', 'Altroz Xz Plus I-Turbo Petrol Dark Edition'),
    ('tiago xta petrol', 'Tiago Xta Petrol'),
    ('tiago xm diesel', 'Tiago Xm Diesel'),
    ('ecosport trend+ 1.5l diesel', 'Ecosport Trend+ 1.5L Diesel'),
    ('vento highline 1.6 mpi', 'Vento Highline 1.6 Mpi'),
    ('seltos gtx at 1.4 petrol', 'Seltos Gtx At 1.4 Petrol'),
    ('glanza g amt', 'Glanza G Amt'),
    ('verna 1.6 sx (o) crdi mt', 'Verna 1.6 Sx (O) Crdi Mt'),
    ('creta sx (o) 1.4 turbo dct dual tone', 'Creta Sx (O) 1.4 Turbo Dct Dual Tone'),
    ('taigun topline 1.0 tsi mt', 'Taigun Topline 1.0 Tsi Mt'),
    ('swift dzire lxi (o)', 'Swift Dzire Lxi (O)'),
    ('kuv100 k8 d 6 str', 'Kuv100 K8 D 6 Str'),
    ('city 1.5l i-vtec v cvt 5th gen', 'City 1.5L I-Vtec V Cvt 5Th Gen'),
    ('go plus a eps', 'Go Plus A Eps'),
    ('punch accomplished mt cng', 'Punch Accomplished Mt Cng'),
    ('venue e 1.2', 'Venue E 1.2'),
    ('nexon xz plus (hs) petrol dark edition', 'Nexon Xz Plus (Hs) Petrol Dark Edition'),
    ('polo comfortline 1.2l', 'Polo Comfortline 1.2L'),
    ('ciaz delta 1.4 mt petrol', 'Ciaz Delta 1.4 Mt Petrol'),
    ('ecosport ambiente 1.5l petrol', 'Ecosport Ambiente 1.5L Petrol'),
    ('glanza g isg', 'Glanza G Isg'),
    ('creta sx plus 1.6 diesel', 'Creta Sx Plus 1.6 Diesel'),
)
TRANSMISSION_OPTIONS = (
    ('automatic', 'Automatic'),
    ('manual', 'Manual'),
)
